### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [sammyhawkrad/ghana-covid-19-dataset#1]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/TW7SXX
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by sammyhawkrad** [comment]
This is interesting to know, I am compiling this dataset because I believe it will be useful to other people.
I'm open to adding the relevant metadata and keeping the dataset up-to-date. Let me know how to go about that.

**Comment by reeshmabijosh** [comment]
Hello*,*

Thanks for your willingness to contribute.
 Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and
you will get the necessary permissions for editing your dataset.
Then please add relevant metadata - description and keywords to your
dataset.
This is an example of a dataset with good metadata
https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/TZMOTL


Thanks
Reeshma K

**Comment by sammyhawkrad** [comment]
I have created the account. How do I make changes to the metadata? And how is the data updated?
